name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10'] 

    steps:
      # Step to check out the repository code
      - uses: actions/checkout@v2

      # Step to set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        
      - name: Auto-commit black formatting
        run: |
          git add .
          git commit -m "Auto-apply black formatting [skip ci]" || echo "No changes to commit"

      # Step to install pre-commit 
      - name: Install pre-commit hooks
        run: pre-commit install

      # Step to run code quality checks
      - name: Run code quality checks
        run: pre-commit run --all-files
